// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcTOl2M2p2HrcJ0wlUxfATX2vqqTvdoo4',
    appId: '1:786419984244:web:71567059ceaaf21b39ae21',
    messagingSenderId: '786419984244',
    projectId: 'noteapp-12f09',
    authDomain: 'noteapp-12f09.firebaseapp.com',
    storageBucket: 'noteapp-12f09.firebasestorage.app',
    measurementId: 'G-FDFVLHTY39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ak0-gwgDDxifL-6pOI0jR2p_CoeJbuY',
    appId: '1:786419984244:android:89582a0ff5cde4a739ae21',
    messagingSenderId: '786419984244',
    projectId: 'noteapp-12f09',
    storageBucket: 'noteapp-12f09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSyQGpWOaf8wZ9iuEX08cPv78OS30XLZ4',
    appId: '1:786419984244:ios:46f0d5e82002332439ae21',
    messagingSenderId: '786419984244',
    projectId: 'noteapp-12f09',
    storageBucket: 'noteapp-12f09.firebasestorage.app',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSyQGpWOaf8wZ9iuEX08cPv78OS30XLZ4',
    appId: '1:786419984244:ios:46f0d5e82002332439ae21',
    messagingSenderId: '786419984244',
    projectId: 'noteapp-12f09',
    storageBucket: 'noteapp-12f09.firebasestorage.app',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcTOl2M2p2HrcJ0wlUxfATX2vqqTvdoo4',
    appId: '1:786419984244:web:df05f682bf1e8c7539ae21',
    messagingSenderId: '786419984244',
    projectId: 'noteapp-12f09',
    authDomain: 'noteapp-12f09.firebaseapp.com',
    storageBucket: 'noteapp-12f09.firebasestorage.app',
    measurementId: 'G-DPFNE774X1',
  );
}
